config/routes.rb
Rails.application.routes.draw do
  resources :members, only: [:new, :create, :index]

#Casein routes
namespace :casein do
    resources :members
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/casein/members_controller.rb
# Scaffolding generated by Casein v5.2.0.0

module Casein
  class MembersController < Casein::CaseinController
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_action :needs_admin, except: [:action1, :action2]
    # before_action :needs_admin_or_current_user, only: [:action1, :action2]
  
    def index
      @casein_page_title = 'Members'
      @members = Member.order(sort_order(:name)).paginate page: params[:page]
    end

    def show
      @casein_page_title = 'View member'
      @member = Member.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new member'
      @member = Member.new
    end

    def create
      @member = Member.new member_params

      if @member.save
        flash[:notice] = 'Member created'
        redirect_to casein_members_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new member'
        render action: :new
      end
    end

    def update
      @casein_page_title = 'Update member'

      @member = Member.find params[:id]

      if @member.update_attributes member_params
        flash[:notice] = 'Member has been updated'
        redirect_to casein_members_path
      else
        flash.now[:warning] = 'There were problems when trying to update this member'
        render action: :show
      end
    end

    def destroy
      @member = Member.find params[:id]

      @member.destroy
      flash[:notice] = 'Member has been deleted'
      redirect_to casein_members_path
    end

    private

    def member_params
      params.require(:member).permit(:name, :phone, :wechat, :suburb, :work, :email, :gender, :dob)
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def new
    @member = Member.new
  end

  def create
    @member = Member.new member_params

    if @member.save
      redirect_to members_path
    else
      render action: :new
    end
  end

  def index
    @members = Member.select(:name, :suburb)
  end

  private

  def member_params
    params.require(:member).permit(:name, :phone, :wechat, :suburb, :work, :email, :gender, :dob)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casein/config_helper.rb
module Casein
  module ConfigHelper
    
    # Name of website or client — used throughout Casein.
    def casein_config_website_name
      'Casein'
    end

    # Filename of logo image. Ideally, it should be a transparent PNG around 140x30px
    def casein_config_logo
      'casein/casein.png'
    end

    # The server hostname where Casein will run
    def casein_config_hostname
      if Rails.env.production?
        'http://www.caseincms.com'
      else
        'http://0.0.0.0:3000'
      end
    end

    # The sender address used for email notifications
    def casein_config_email_from_address
      'donotreply@caseincms.com'
    end
  
    # The initial page the user is shown after they sign in or click the logo. Probably this should be set to the first tab.
    # Do not point this at casein/index!
    def casein_config_dashboard_url
      url_for controller: :casein, action: :blank
    end
  
    # A list of stylesheets to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_stylesheet_includes
      %w[casein/casein casein/custom]
    end
  
    # A list of JavaScript files to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_javascript_includes
      %w[casein/casein casein/custom]
    end

     # A list of stylesheets to include in the authentication layout. Do not remove the core casein/login, but you can change the load order, if required.
    def casein_config_auth_stylesheet_includes
      %w[casein/login casein/auth_custom]
    end
  
    # A list of JavaScript files to includein the authentication layout. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_auth_javascript_includes
      %w[casein/casein casein/auth_custom]
    end
    
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/casein/layouts/_tab_navigation.html.erb
<!-- NOTE: the casein:scaffold generator automatically appends new controllers to this file. The SCAFFOLD_INSERT line must NOT be removed -->
<!-- SCAFFOLD_INSERT -->
<li id="tab-members"><%= link_to "Members", casein_members_path %></li>

app/views/casein/layouts/_top_navigation.html.erb
<!-- NOTE: add "hidden-xs hidden-sm" class to li elements you want to be hidden at small browser widths -->
<!-- e.g. <li class="hidden-xs hidden-sm"><%= link_to "Visit site", casein_config_hostname, target: "_blank" %></li> -->

<li><%= link_to "Visit site", casein_config_hostname, target: "_blank" %></li>

app/views/casein/members/_form.html.erb
<!-- Scaffolding generated by Casein v5.2.0.0 -->


<div class="row">
  <div class="col-lg-6">
    <%= casein_text_field f, f.object, :name %>
  </div>
  <div class="col-lg-6">
    <%= casein_text_field f, f.object, :phone %>
  </div>
</div>

<div class="row">
  <div class="col-lg-6">
    <%= casein_text_field f, f.object, :wechat %>
  </div>
  <div class="col-lg-6">
    <%= casein_text_field f, f.object, :suburb %>
  </div>
</div>

<div class="row">
  <div class="col-lg-6">
    <%= casein_text_field f, f.object, :work %>
  </div>
  <div class="col-lg-6">
    <%= casein_text_field f, f.object, :email %>
  </div>
</div>

<div class="row">
  <div class="col-lg-6">
    <%= casein_text_field f, f.object, :gender %>
  </div>
  <div class="col-lg-6">
    <%= casein_date_select f, f.object, :dob %>
  </div>
</div>

app/views/casein/members/_table.html.erb
<!-- Scaffolding generated by Casein v5.2.0.0 -->

<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th><%= casein_sort_link "Name", :name %></th>
      <th><%= casein_sort_link "Phone", :phone %></th>
      <th><%= casein_sort_link "Wechat", :wechat %></th>
      <th><%= casein_sort_link "Suburb", :suburb %></th>
      <th><%= casein_sort_link "Work", :work %></th>
      <th><%= casein_sort_link "Email", :email %></th>
      <th><%= casein_sort_link "Gender", :gender %></th>
      <th><%= casein_sort_link "Dob", :dob %></th>
      <th>&nbsp;</th>
    </tr>
  </thead>

  <% members.each do |member| %>
    <tr>
      <td><%= casein_table_cell_link member.name, casein_member_path(member) %></td>
      <td><%= casein_table_cell_link member.phone, casein_member_path(member) %></td>
      <td><%= casein_table_cell_link member.wechat, casein_member_path(member) %></td>
      <td><%= casein_table_cell_link member.suburb, casein_member_path(member) %></td>
      <td><%= casein_table_cell_link member.work, casein_member_path(member) %></td>
      <td><%= casein_table_cell_link member.email, casein_member_path(member) %></td>
      <td><%= casein_table_cell_link member.gender, casein_member_path(member) %></td>
      <td><%= casein_table_cell_link member.dob, casein_member_path(member) %></td>
      <td class="delete">
        <%= link_to(casein_show_row_icon("trash"), casein_member_path(member), method: :delete, data: { confirm: "Are you sure you want to delete this member?" }) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/casein/members/index.html.erb
<!-- Scaffolding generated by Casein v5.2.0.0 -->

<h2>Members<%= casein_pagination_details @members %></h2>

<%= render partial: 'casein/members/table', locals: { members: @members } %>

<div class="text-center">
  <%= will_paginate @members %>
</div>

<%= content_for :sidebar do %>

  <li><%= link_to "#{casein_show_icon "plus-sign"}Add a new member".html_safe, new_casein_member_path %></li>

<% end %>

app/views/casein/members/new.html.erb
<!-- Scaffolding generated by Casein v5.2.0.0 -->

<h2>Add a new member</h2>

<%= form_for @member, url: casein_members_path do |f| %>

  <%= render partial: 'casein/members/form', locals: { f: f } %>

  <p class="submits">
    <%= link_to 'Cancel', casein_members_path, class: 'btn btn-mini btn-danger' %>
    <%= f.submit "Add new member", class: "btn btn-mini btn-primary" %>
  </p>

<% end %>

<%= content_for :sidebar do %>
  <li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_members_path %></li>
<% end %>

app/views/casein/members/show.html.erb
<!-- Scaffolding generated by Casein v5.2.0.0 -->

<h2>View member</h2>

<%= form_for @member, url: casein_member_path(@member) do |f| %>

  <%= render partial: 'casein/members/form', locals: { f: f } %>

  <p class="submits">
      <%= link_to 'Cancel', casein_members_path, class: 'btn btn-mini btn-danger' %>
    <%= f.submit "Save changes", class: "btn btn-mini btn-primary" %>
  </p>

<% end %>

<%= content_for :sidebar do %>
  <li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_members_path %></li>
<% end %>

app/views/layouts/_header.html.erb
<div>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <!-- <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active">
          <a href="#">加入</a>
        </li>
        <li>
          <a href="#">同乡会成员</a>
        </li>
        <li>
          <a href="#">关于联谊同乡会</a>
        </li>
      </ul>
    </div> -->
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Brand</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">同乡会成员<span class="sr-only">(current)</span></a></li>
          <li><a href="#">关于联谊同乡会</a></li>
        </ul>
        <form class="navbar-form navbar-left">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#">加入</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZhanjiangTownsman</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/members/index.html.erb
<h2>澳大利亚湛江同乡联谊会会员</h2>
<div class="row">
  <% @members.each do |member| %>
    <div class="col-sm-4 col-md-3 ">
      <div class="thumbnail">
        <img src="http://placehold.it/200x150" alt="...">
        <div class="caption text-center">
          <h3><%= member.name %></h3>
          <p><%= member.suburb %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/members/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h2>加入同乡联谊会</h2>
    <%= simple_form_for @member do |f| %>
      <%= f.input :name, label: '姓名' %>
      <%= f.input :phone, label: '电话' %>
      <%= f.input :wechat, label: '微信号' %>
      <%= f.input :suburb, label: '澳洲所在城市' %>
      <%= f.input :work, label: '职业' %>
      <%= f.input :email, label: '邮件' %>
      <%= f.button :submit, class: 'btn-primary' %>
    <% end %>
  </div>
</div>